<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Lunar\LunarException'                                => __DIR__ . '/../src/Lunar/LunarException.php',
    'Lunar\I18n\Translation\Module'                       => __DIR__ . '/../src/Lunar/I18n/Translation/Module.php',
    'Lunar\I18n\Translation\ModuleException'              => __DIR__ . '/../src/Lunar/I18n/Translation/ModuleException.php',
    'Lunar\I18n\Translation\Catalogue\CatalogueInterface' => __DIR__ . '/../src/Lunar/I18n/Translation/Catalogue/CatalogueInterface.php',
    'Lunar\I18n\Translation\Catalogue\AclResources'       => __DIR__ . '/../src/Lunar/I18n/Translation/Catalogue/AclResources.php',
    'Lunar\I18n\Translation\Catalogue\AbstractCatalogue'  => __DIR__ . '/../src/Lunar/I18n/Translation/Catalogue/AbstractCatalogue.php',
    'Lunar\I18n\Translation\Adapter\GettextAdapter'       => __DIR__ . '/../src/Lunar/I18n/Translation/Adapter/GettextAdapter.php',
    'Lunar\I18n\Translation\Adapter\TranslationAdapter'   => __DIR__ . '/../src/Lunar/I18n/Translation/Adapter/TranslationAdapter.php',
    'Lunar\I18n\Translation\Message'                      => __DIR__ . '/../src/Lunar/I18n/Translation/Message.php',
    'Lunar\I18n\Translation\Source'                       => __DIR__ . '/../src/Lunar/I18n/Translation/Source.php',
    'Lunar\I18n\Translation\Translator'                   => __DIR__ . '/../src/Lunar/I18n/Translation/Translator.php',
    'Lunar\I18n\Translation\TranslationException'         => __DIR__ . '/../src/Lunar/I18n/Translation/TranslationException.php',
    'Lunar\I18n\Translation\Script'                       => __DIR__ . '/../src/Lunar/I18n/Translation/Script.php',
    'Lunar\I18n\I18nException'                            => __DIR__ . '/../src/Lunar/I18n/I18nException.php',
);
